//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: shake_escrow
// ----------------------------------------------------------------------------
pub mod shake_escrow {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for shake_escrow
    pub fn program_id() -> Pubkey {
        pubkey!("Hv4f6R9GgZ9nvK8HvA3KYwxPTrmiqyiE9KFvrENjgD67")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: AcceptAdmin
    // ....................................................................

    /// Main instruction struct for AcceptAdmin
    pub struct AcceptAdminInstruction {
        pub accounts: AcceptAdminInstructionAccountMetas,
        pub data: AcceptAdminInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for AcceptAdmin instruction
    #[derive(Debug, Clone, Default)]
    pub struct AcceptAdminInstructionAccountMetas {
        pub new_admin: AccountMeta,

        pub config: AccountMeta,

        pub admin_transfer: AccountMeta,

        pub previous_admin: AccountMeta,

        pub event_authority: AccountMeta,

        pub program: AccountMeta,
    }

    /// Account pubkeys for AcceptAdmin instruction
    #[derive(Debug, Clone)]
    pub struct AcceptAdminInstructionAccounts {
        pub new_admin: Pubkey,

        pub config: Pubkey,

        pub admin_transfer: Pubkey,

        pub previous_admin: Pubkey,

        pub event_authority: Pubkey,

        pub program: Pubkey,
    }

    impl AcceptAdminInstructionAccounts {
        pub fn new(
            new_admin: Pubkey,

            config: Pubkey,

            admin_transfer: Pubkey,

            previous_admin: Pubkey,

            event_authority: Pubkey,

            program: Pubkey,
        ) -> Self {
            Self {
                new_admin,

                config,

                admin_transfer,

                previous_admin,

                event_authority,

                program,
            }
        }
    }

    /// Instruction data for AcceptAdmin
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct AcceptAdminInstructionData {}

    impl AcceptAdminInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for AcceptAdminInstruction
    impl AcceptAdminInstruction {
        fn discriminator() -> [u8; 8] {
            [112u8, 42u8, 45u8, 90u8, 116u8, 181u8, 13u8, 170u8]
        }

        pub fn data(data: AcceptAdminInstructionData) -> Self {
            Self {
                accounts: AcceptAdminInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: AcceptAdminInstructionAccounts) -> Self {
            self.accounts.new_admin = AccountMeta::new_readonly(accounts.new_admin, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.admin_transfer = AccountMeta::new(accounts.admin_transfer, false);

            self.accounts.previous_admin = AccountMeta::new(accounts.previous_admin, false);

            self.accounts.event_authority =
                AccountMeta::new_readonly(accounts.event_authority, false);

            self.accounts.program = AccountMeta::new_readonly(accounts.program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.new_admin.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.admin_transfer.clone());

            metas.push(self.accounts.previous_admin.clone());

            metas.push(self.accounts.event_authority.clone());

            metas.push(self.accounts.program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CancelAccept
    // ....................................................................

    /// Main instruction struct for CancelAccept
    pub struct CancelAcceptInstruction {
        pub accounts: CancelAcceptInstructionAccountMetas,
        pub data: CancelAcceptInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CancelAccept instruction
    #[derive(Debug, Clone, Default)]
    pub struct CancelAcceptInstructionAccountMetas {
        pub acceptor: AccountMeta,

        pub config: AccountMeta,

        pub wager: AccountMeta,

        pub side_a: AccountMeta,

        pub side_b: AccountMeta,

        pub side_a_token: AccountMeta,

        pub side_b_token: AccountMeta,

        pub counter_a: AccountMeta,

        pub counter_b: AccountMeta,

        pub fee_token: AccountMeta,

        pub vault: AccountMeta,

        pub rent_collector: AccountMeta,

        pub token_program: AccountMeta,

        pub event_authority: AccountMeta,

        pub program: AccountMeta,
    }

    /// Account pubkeys for CancelAccept instruction
    #[derive(Debug, Clone)]
    pub struct CancelAcceptInstructionAccounts {
        pub acceptor: Pubkey,

        pub config: Pubkey,

        pub wager: Pubkey,

        pub side_a: Pubkey,

        pub side_b: Pubkey,

        pub side_a_token: Pubkey,

        pub side_b_token: Pubkey,

        pub counter_a: Pubkey,

        pub counter_b: Pubkey,

        pub fee_token: Pubkey,

        pub vault: Pubkey,

        pub rent_collector: Pubkey,

        pub event_authority: Pubkey,

        pub program: Pubkey,
    }

    impl CancelAcceptInstructionAccounts {
        pub fn new(
            acceptor: Pubkey,

            config: Pubkey,

            wager: Pubkey,

            side_a: Pubkey,

            side_b: Pubkey,

            side_a_token: Pubkey,

            side_b_token: Pubkey,

            counter_a: Pubkey,

            counter_b: Pubkey,

            fee_token: Pubkey,

            vault: Pubkey,

            rent_collector: Pubkey,

            event_authority: Pubkey,

            program: Pubkey,
        ) -> Self {
            Self {
                acceptor,

                config,

                wager,

                side_a,

                side_b,

                side_a_token,

                side_b_token,

                counter_a,

                counter_b,

                fee_token,

                vault,

                rent_collector,

                event_authority,

                program,
            }
        }
    }

    /// Instruction data for CancelAccept
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CancelAcceptInstructionData {}

    impl CancelAcceptInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for CancelAcceptInstruction
    impl CancelAcceptInstruction {
        fn discriminator() -> [u8; 8] {
            [238u8, 198u8, 11u8, 182u8, 13u8, 108u8, 81u8, 95u8]
        }

        pub fn data(data: CancelAcceptInstructionData) -> Self {
            Self {
                accounts: CancelAcceptInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CancelAcceptInstructionAccounts) -> Self {
            self.accounts.acceptor = AccountMeta::new_readonly(accounts.acceptor, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.wager = AccountMeta::new(accounts.wager, false);

            self.accounts.side_a = AccountMeta::new_readonly(accounts.side_a, false);

            self.accounts.side_b = AccountMeta::new_readonly(accounts.side_b, false);

            self.accounts.side_a_token = AccountMeta::new(accounts.side_a_token, false);

            self.accounts.side_b_token = AccountMeta::new(accounts.side_b_token, false);

            self.accounts.counter_a = AccountMeta::new(accounts.counter_a, false);

            self.accounts.counter_b = AccountMeta::new(accounts.counter_b, false);

            self.accounts.fee_token = AccountMeta::new(accounts.fee_token, false);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.rent_collector = AccountMeta::new(accounts.rent_collector, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self.accounts.event_authority =
                AccountMeta::new_readonly(accounts.event_authority, false);

            self.accounts.program = AccountMeta::new_readonly(accounts.program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.acceptor.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.wager.clone());

            metas.push(self.accounts.side_a.clone());

            metas.push(self.accounts.side_b.clone());

            metas.push(self.accounts.side_a_token.clone());

            metas.push(self.accounts.side_b_token.clone());

            metas.push(self.accounts.counter_a.clone());

            metas.push(self.accounts.counter_b.clone());

            metas.push(self.accounts.fee_token.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.rent_collector.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.event_authority.clone());

            metas.push(self.accounts.program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CancelAdminTransfer
    // ....................................................................

    /// Main instruction struct for CancelAdminTransfer
    pub struct CancelAdminTransferInstruction {
        pub accounts: CancelAdminTransferInstructionAccountMetas,
        pub data: CancelAdminTransferInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CancelAdminTransfer instruction
    #[derive(Debug, Clone, Default)]
    pub struct CancelAdminTransferInstructionAccountMetas {
        pub admin: AccountMeta,

        pub config: AccountMeta,

        pub admin_transfer: AccountMeta,

        pub event_authority: AccountMeta,

        pub program: AccountMeta,
    }

    /// Account pubkeys for CancelAdminTransfer instruction
    #[derive(Debug, Clone)]
    pub struct CancelAdminTransferInstructionAccounts {
        pub admin: Pubkey,

        pub config: Pubkey,

        pub admin_transfer: Pubkey,

        pub event_authority: Pubkey,

        pub program: Pubkey,
    }

    impl CancelAdminTransferInstructionAccounts {
        pub fn new(
            admin: Pubkey,

            config: Pubkey,

            admin_transfer: Pubkey,

            event_authority: Pubkey,

            program: Pubkey,
        ) -> Self {
            Self {
                admin,

                config,

                admin_transfer,

                event_authority,

                program,
            }
        }
    }

    /// Instruction data for CancelAdminTransfer
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CancelAdminTransferInstructionData {}

    impl CancelAdminTransferInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for CancelAdminTransferInstruction
    impl CancelAdminTransferInstruction {
        fn discriminator() -> [u8; 8] {
            [38u8, 131u8, 157u8, 31u8, 240u8, 137u8, 44u8, 215u8]
        }

        pub fn data(data: CancelAdminTransferInstructionData) -> Self {
            Self {
                accounts: CancelAdminTransferInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CancelAdminTransferInstructionAccounts) -> Self {
            self.accounts.admin = AccountMeta::new(accounts.admin, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.admin_transfer = AccountMeta::new(accounts.admin_transfer, false);

            self.accounts.event_authority =
                AccountMeta::new_readonly(accounts.event_authority, false);

            self.accounts.program = AccountMeta::new_readonly(accounts.program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.admin_transfer.clone());

            metas.push(self.accounts.event_authority.clone());

            metas.push(self.accounts.program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CancelClear
    // ....................................................................

    /// Main instruction struct for CancelClear
    pub struct CancelClearInstruction {
        pub accounts: CancelClearInstructionAccountMetas,
        pub data: CancelClearInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CancelClear instruction
    #[derive(Debug, Clone, Default)]
    pub struct CancelClearInstructionAccountMetas {
        pub participant: AccountMeta,

        pub wager: AccountMeta,

        pub event_authority: AccountMeta,

        pub program: AccountMeta,
    }

    /// Account pubkeys for CancelClear instruction
    #[derive(Debug, Clone)]
    pub struct CancelClearInstructionAccounts {
        pub participant: Pubkey,

        pub wager: Pubkey,

        pub event_authority: Pubkey,

        pub program: Pubkey,
    }

    impl CancelClearInstructionAccounts {
        pub fn new(
            participant: Pubkey,

            wager: Pubkey,

            event_authority: Pubkey,

            program: Pubkey,
        ) -> Self {
            Self {
                participant,

                wager,

                event_authority,

                program,
            }
        }
    }

    /// Instruction data for CancelClear
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CancelClearInstructionData {}

    impl CancelClearInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for CancelClearInstruction
    impl CancelClearInstruction {
        fn discriminator() -> [u8; 8] {
            [145u8, 6u8, 252u8, 203u8, 185u8, 13u8, 229u8, 32u8]
        }

        pub fn data(data: CancelClearInstructionData) -> Self {
            Self {
                accounts: CancelClearInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CancelClearInstructionAccounts) -> Self {
            self.accounts.participant = AccountMeta::new_readonly(accounts.participant, true);

            self.accounts.wager = AccountMeta::new(accounts.wager, false);

            self.accounts.event_authority =
                AccountMeta::new_readonly(accounts.event_authority, false);

            self.accounts.program = AccountMeta::new_readonly(accounts.program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.participant.clone());

            metas.push(self.accounts.wager.clone());

            metas.push(self.accounts.event_authority.clone());

            metas.push(self.accounts.program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CancelPropose
    // ....................................................................

    /// Main instruction struct for CancelPropose
    pub struct CancelProposeInstruction {
        pub accounts: CancelProposeInstructionAccountMetas,
        pub data: CancelProposeInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CancelPropose instruction
    #[derive(Debug, Clone, Default)]
    pub struct CancelProposeInstructionAccountMetas {
        pub participant: AccountMeta,

        pub wager: AccountMeta,

        pub event_authority: AccountMeta,

        pub program: AccountMeta,
    }

    /// Account pubkeys for CancelPropose instruction
    #[derive(Debug, Clone)]
    pub struct CancelProposeInstructionAccounts {
        pub participant: Pubkey,

        pub wager: Pubkey,

        pub event_authority: Pubkey,

        pub program: Pubkey,
    }

    impl CancelProposeInstructionAccounts {
        pub fn new(
            participant: Pubkey,

            wager: Pubkey,

            event_authority: Pubkey,

            program: Pubkey,
        ) -> Self {
            Self {
                participant,

                wager,

                event_authority,

                program,
            }
        }
    }

    /// Instruction data for CancelPropose
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CancelProposeInstructionData {}

    impl CancelProposeInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for CancelProposeInstruction
    impl CancelProposeInstruction {
        fn discriminator() -> [u8; 8] {
            [26u8, 234u8, 145u8, 66u8, 243u8, 176u8, 98u8, 167u8]
        }

        pub fn data(data: CancelProposeInstructionData) -> Self {
            Self {
                accounts: CancelProposeInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CancelProposeInstructionAccounts) -> Self {
            self.accounts.participant = AccountMeta::new_readonly(accounts.participant, true);

            self.accounts.wager = AccountMeta::new(accounts.wager, false);

            self.accounts.event_authority =
                AccountMeta::new_readonly(accounts.event_authority, false);

            self.accounts.program = AccountMeta::new_readonly(accounts.program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.participant.clone());

            metas.push(self.accounts.wager.clone());

            metas.push(self.accounts.event_authority.clone());

            metas.push(self.accounts.program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CloseExpired
    // ....................................................................

    /// Main instruction struct for CloseExpired
    pub struct CloseExpiredInstruction {
        pub accounts: CloseExpiredInstructionAccountMetas,
        pub data: CloseExpiredInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CloseExpired instruction
    #[derive(Debug, Clone, Default)]
    pub struct CloseExpiredInstructionAccountMetas {
        pub cranker: AccountMeta,

        pub wager: AccountMeta,

        pub vault: AccountMeta,

        pub fee_token: AccountMeta,

        pub rent_collector: AccountMeta,

        pub token_program: AccountMeta,

        pub event_authority: AccountMeta,

        pub program: AccountMeta,
    }

    /// Account pubkeys for CloseExpired instruction
    #[derive(Debug, Clone)]
    pub struct CloseExpiredInstructionAccounts {
        pub cranker: Pubkey,

        pub wager: Pubkey,

        pub vault: Pubkey,

        pub fee_token: Pubkey,

        pub rent_collector: Pubkey,

        pub event_authority: Pubkey,

        pub program: Pubkey,
    }

    impl CloseExpiredInstructionAccounts {
        pub fn new(
            cranker: Pubkey,

            wager: Pubkey,

            vault: Pubkey,

            fee_token: Pubkey,

            rent_collector: Pubkey,

            event_authority: Pubkey,

            program: Pubkey,
        ) -> Self {
            Self {
                cranker,

                wager,

                vault,

                fee_token,

                rent_collector,

                event_authority,

                program,
            }
        }
    }

    /// Instruction data for CloseExpired
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CloseExpiredInstructionData {}

    impl CloseExpiredInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for CloseExpiredInstruction
    impl CloseExpiredInstruction {
        fn discriminator() -> [u8; 8] {
            [138u8, 186u8, 164u8, 245u8, 32u8, 116u8, 162u8, 62u8]
        }

        pub fn data(data: CloseExpiredInstructionData) -> Self {
            Self {
                accounts: CloseExpiredInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CloseExpiredInstructionAccounts) -> Self {
            self.accounts.cranker = AccountMeta::new_readonly(accounts.cranker, true);

            self.accounts.wager = AccountMeta::new(accounts.wager, false);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.fee_token = AccountMeta::new(accounts.fee_token, false);

            self.accounts.rent_collector = AccountMeta::new(accounts.rent_collector, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self.accounts.event_authority =
                AccountMeta::new_readonly(accounts.event_authority, false);

            self.accounts.program = AccountMeta::new_readonly(accounts.program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.cranker.clone());

            metas.push(self.accounts.wager.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.fee_token.clone());

            metas.push(self.accounts.rent_collector.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.event_authority.clone());

            metas.push(self.accounts.program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Concede
    // ....................................................................

    /// Main instruction struct for Concede
    pub struct ConcedeInstruction {
        pub accounts: ConcedeInstructionAccountMetas,
        pub data: ConcedeInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Concede instruction
    #[derive(Debug, Clone, Default)]
    pub struct ConcedeInstructionAccountMetas {
        pub conceder: AccountMeta,

        pub config: AccountMeta,

        pub wager: AccountMeta,

        pub winner: AccountMeta,

        pub winner_token: AccountMeta,

        pub fee_token: AccountMeta,

        pub vault: AccountMeta,

        pub counter_a: AccountMeta,

        pub counter_b: AccountMeta,

        pub rent_collector: AccountMeta,

        pub token_program: AccountMeta,

        pub event_authority: AccountMeta,

        pub program: AccountMeta,
    }

    /// Account pubkeys for Concede instruction
    #[derive(Debug, Clone)]
    pub struct ConcedeInstructionAccounts {
        pub conceder: Pubkey,

        pub config: Pubkey,

        pub wager: Pubkey,

        pub winner: Pubkey,

        pub winner_token: Pubkey,

        pub fee_token: Pubkey,

        pub vault: Pubkey,

        pub counter_a: Pubkey,

        pub counter_b: Pubkey,

        pub rent_collector: Pubkey,

        pub event_authority: Pubkey,

        pub program: Pubkey,
    }

    impl ConcedeInstructionAccounts {
        pub fn new(
            conceder: Pubkey,

            config: Pubkey,

            wager: Pubkey,

            winner: Pubkey,

            winner_token: Pubkey,

            fee_token: Pubkey,

            vault: Pubkey,

            counter_a: Pubkey,

            counter_b: Pubkey,

            rent_collector: Pubkey,

            event_authority: Pubkey,

            program: Pubkey,
        ) -> Self {
            Self {
                conceder,

                config,

                wager,

                winner,

                winner_token,

                fee_token,

                vault,

                counter_a,

                counter_b,

                rent_collector,

                event_authority,

                program,
            }
        }
    }

    /// Instruction data for Concede
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ConcedeInstructionData {}

    impl ConcedeInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for ConcedeInstruction
    impl ConcedeInstruction {
        fn discriminator() -> [u8; 8] {
            [19u8, 182u8, 3u8, 3u8, 43u8, 35u8, 60u8, 202u8]
        }

        pub fn data(data: ConcedeInstructionData) -> Self {
            Self {
                accounts: ConcedeInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ConcedeInstructionAccounts) -> Self {
            self.accounts.conceder = AccountMeta::new_readonly(accounts.conceder, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.wager = AccountMeta::new(accounts.wager, false);

            self.accounts.winner = AccountMeta::new_readonly(accounts.winner, false);

            self.accounts.winner_token = AccountMeta::new(accounts.winner_token, false);

            self.accounts.fee_token = AccountMeta::new(accounts.fee_token, false);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.counter_a = AccountMeta::new(accounts.counter_a, false);

            self.accounts.counter_b = AccountMeta::new(accounts.counter_b, false);

            self.accounts.rent_collector = AccountMeta::new(accounts.rent_collector, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self.accounts.event_authority =
                AccountMeta::new_readonly(accounts.event_authority, false);

            self.accounts.program = AccountMeta::new_readonly(accounts.program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.conceder.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.wager.clone());

            metas.push(self.accounts.winner.clone());

            metas.push(self.accounts.winner_token.clone());

            metas.push(self.accounts.fee_token.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.counter_a.clone());

            metas.push(self.accounts.counter_b.clone());

            metas.push(self.accounts.rent_collector.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.event_authority.clone());

            metas.push(self.accounts.program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CreateWager
    // ....................................................................

    /// Main instruction struct for CreateWager
    pub struct CreateWagerInstruction {
        pub accounts: CreateWagerInstructionAccountMetas,
        pub data: CreateWagerInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CreateWager instruction
    #[derive(Debug, Clone, Default)]
    pub struct CreateWagerInstructionAccountMetas {
        pub payer: AccountMeta,

        pub config: AccountMeta,

        pub wager: AccountMeta,

        pub mint: AccountMeta,

        pub vault: AccountMeta,

        pub token_program: AccountMeta,

        pub associated_token_program: AccountMeta,

        pub system_program: AccountMeta,

        pub event_authority: AccountMeta,

        pub program: AccountMeta,
    }

    /// Account pubkeys for CreateWager instruction
    #[derive(Debug, Clone)]
    pub struct CreateWagerInstructionAccounts {
        pub payer: Pubkey,

        pub config: Pubkey,

        pub wager: Pubkey,

        pub mint: Pubkey,

        pub vault: Pubkey,

        pub event_authority: Pubkey,

        pub program: Pubkey,
    }

    impl CreateWagerInstructionAccounts {
        pub fn new(
            payer: Pubkey,

            config: Pubkey,

            wager: Pubkey,

            mint: Pubkey,

            vault: Pubkey,

            event_authority: Pubkey,

            program: Pubkey,
        ) -> Self {
            Self {
                payer,

                config,

                wager,

                mint,

                vault,

                event_authority,

                program,
            }
        }
    }

    /// Instruction data for CreateWager
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CreateWagerInstructionData {
        pub args: CreateWagerArgs,
    }

    impl CreateWagerInstructionData {
        pub fn new(args: CreateWagerArgs) -> Self {
            Self { args }
        }
    }

    /// Implementation for CreateWagerInstruction
    impl CreateWagerInstruction {
        fn discriminator() -> [u8; 8] {
            [210u8, 82u8, 178u8, 75u8, 253u8, 34u8, 84u8, 120u8]
        }

        pub fn data(data: CreateWagerInstructionData) -> Self {
            Self {
                accounts: CreateWagerInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CreateWagerInstructionAccounts) -> Self {
            self.accounts.payer = AccountMeta::new(accounts.payer, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.wager = AccountMeta::new(accounts.wager, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self.accounts.associated_token_program = AccountMeta::new_readonly(
                pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
                false,
            );

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self.accounts.event_authority =
                AccountMeta::new_readonly(accounts.event_authority, false);

            self.accounts.program = AccountMeta::new_readonly(accounts.program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.payer.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.wager.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.associated_token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.push(self.accounts.event_authority.clone());

            metas.push(self.accounts.program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: InitializeConfig
    // ....................................................................

    /// Main instruction struct for InitializeConfig
    pub struct InitializeConfigInstruction {
        pub accounts: InitializeConfigInstructionAccountMetas,
        pub data: InitializeConfigInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for InitializeConfig instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeConfigInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub program: AccountMeta,

        pub program_data: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for InitializeConfig instruction
    #[derive(Debug, Clone)]
    pub struct InitializeConfigInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub program_data: Pubkey,
    }

    impl InitializeConfigInstructionAccounts {
        pub fn new(authority: Pubkey, config: Pubkey, program_data: Pubkey) -> Self {
            Self {
                authority,

                config,

                program_data,
            }
        }
    }

    /// Instruction data for InitializeConfig
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeConfigInstructionData {
        pub args: InitializeConfigArgs,
    }

    impl InitializeConfigInstructionData {
        pub fn new(args: InitializeConfigArgs) -> Self {
            Self { args }
        }
    }

    /// Implementation for InitializeConfigInstruction
    impl InitializeConfigInstruction {
        fn discriminator() -> [u8; 8] {
            [208u8, 127u8, 21u8, 1u8, 194u8, 190u8, 196u8, 70u8]
        }

        pub fn data(data: InitializeConfigInstructionData) -> Self {
            Self {
                accounts: InitializeConfigInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializeConfigInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.program = AccountMeta::new_readonly(
                pubkey!("Hv4f6R9GgZ9nvK8HvA3KYwxPTrmiqyiE9KFvrENjgD67"),
                false,
            );

            self.accounts.program_data = AccountMeta::new_readonly(accounts.program_data, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.program.clone());

            metas.push(self.accounts.program_data.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: ProposeAdmin
    // ....................................................................

    /// Main instruction struct for ProposeAdmin
    pub struct ProposeAdminInstruction {
        pub accounts: ProposeAdminInstructionAccountMetas,
        pub data: ProposeAdminInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for ProposeAdmin instruction
    #[derive(Debug, Clone, Default)]
    pub struct ProposeAdminInstructionAccountMetas {
        pub admin: AccountMeta,

        pub config: AccountMeta,

        pub admin_transfer: AccountMeta,

        pub system_program: AccountMeta,

        pub event_authority: AccountMeta,

        pub program: AccountMeta,
    }

    /// Account pubkeys for ProposeAdmin instruction
    #[derive(Debug, Clone)]
    pub struct ProposeAdminInstructionAccounts {
        pub admin: Pubkey,

        pub config: Pubkey,

        pub admin_transfer: Pubkey,

        pub event_authority: Pubkey,

        pub program: Pubkey,
    }

    impl ProposeAdminInstructionAccounts {
        pub fn new(
            admin: Pubkey,

            config: Pubkey,

            admin_transfer: Pubkey,

            event_authority: Pubkey,

            program: Pubkey,
        ) -> Self {
            Self {
                admin,

                config,

                admin_transfer,

                event_authority,

                program,
            }
        }
    }

    /// Instruction data for ProposeAdmin
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ProposeAdminInstructionData {
        pub new_admin: Pubkey,
    }

    impl ProposeAdminInstructionData {
        pub fn new(new_admin: Pubkey) -> Self {
            Self { new_admin }
        }
    }

    /// Implementation for ProposeAdminInstruction
    impl ProposeAdminInstruction {
        fn discriminator() -> [u8; 8] {
            [121u8, 214u8, 199u8, 212u8, 87u8, 39u8, 117u8, 234u8]
        }

        pub fn data(data: ProposeAdminInstructionData) -> Self {
            Self {
                accounts: ProposeAdminInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ProposeAdminInstructionAccounts) -> Self {
            self.accounts.admin = AccountMeta::new(accounts.admin, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.admin_transfer = AccountMeta::new(accounts.admin_transfer, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self.accounts.event_authority =
                AccountMeta::new_readonly(accounts.event_authority, false);

            self.accounts.program = AccountMeta::new_readonly(accounts.program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.admin_transfer.clone());

            metas.push(self.accounts.system_program.clone());

            metas.push(self.accounts.event_authority.clone());

            metas.push(self.accounts.program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: RefundSide
    // ....................................................................

    /// Main instruction struct for RefundSide
    pub struct RefundSideInstruction {
        pub accounts: RefundSideInstructionAccountMetas,
        pub data: RefundSideInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for RefundSide instruction
    #[derive(Debug, Clone, Default)]
    pub struct RefundSideInstructionAccountMetas {
        pub cranker: AccountMeta,

        pub config: AccountMeta,

        pub wager: AccountMeta,

        pub side: AccountMeta,

        pub side_token: AccountMeta,

        pub counter: AccountMeta,

        pub vault: AccountMeta,

        pub token_program: AccountMeta,

        pub event_authority: AccountMeta,

        pub program: AccountMeta,
    }

    /// Account pubkeys for RefundSide instruction
    #[derive(Debug, Clone)]
    pub struct RefundSideInstructionAccounts {
        pub cranker: Pubkey,

        pub config: Pubkey,

        pub wager: Pubkey,

        pub side: Pubkey,

        pub side_token: Pubkey,

        pub counter: Pubkey,

        pub vault: Pubkey,

        pub event_authority: Pubkey,

        pub program: Pubkey,
    }

    impl RefundSideInstructionAccounts {
        pub fn new(
            cranker: Pubkey,

            config: Pubkey,

            wager: Pubkey,

            side: Pubkey,

            side_token: Pubkey,

            counter: Pubkey,

            vault: Pubkey,

            event_authority: Pubkey,

            program: Pubkey,
        ) -> Self {
            Self {
                cranker,

                config,

                wager,

                side,

                side_token,

                counter,

                vault,

                event_authority,

                program,
            }
        }
    }

    /// Instruction data for RefundSide
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct RefundSideInstructionData {}

    impl RefundSideInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for RefundSideInstruction
    impl RefundSideInstruction {
        fn discriminator() -> [u8; 8] {
            [82u8, 211u8, 109u8, 116u8, 111u8, 44u8, 242u8, 156u8]
        }

        pub fn data(data: RefundSideInstructionData) -> Self {
            Self {
                accounts: RefundSideInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: RefundSideInstructionAccounts) -> Self {
            self.accounts.cranker = AccountMeta::new_readonly(accounts.cranker, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.wager = AccountMeta::new(accounts.wager, false);

            self.accounts.side = AccountMeta::new_readonly(accounts.side, false);

            self.accounts.side_token = AccountMeta::new(accounts.side_token, false);

            self.accounts.counter = AccountMeta::new(accounts.counter, false);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self.accounts.event_authority =
                AccountMeta::new_readonly(accounts.event_authority, false);

            self.accounts.program = AccountMeta::new_readonly(accounts.program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.cranker.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.wager.clone());

            metas.push(self.accounts.side.clone());

            metas.push(self.accounts.side_token.clone());

            metas.push(self.accounts.counter.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.event_authority.clone());

            metas.push(self.accounts.program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Resolve
    // ....................................................................

    /// Main instruction struct for Resolve
    pub struct ResolveInstruction {
        pub accounts: ResolveInstructionAccountMetas,
        pub data: ResolveInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Resolve instruction
    #[derive(Debug, Clone, Default)]
    pub struct ResolveInstructionAccountMetas {
        pub resolver: AccountMeta,

        pub config: AccountMeta,

        pub wager: AccountMeta,

        pub winner: AccountMeta,

        pub winner_token: AccountMeta,

        pub fee_token: AccountMeta,

        pub vault: AccountMeta,

        pub counter_a: AccountMeta,

        pub counter_b: AccountMeta,

        pub rent_collector: AccountMeta,

        pub token_program: AccountMeta,

        pub event_authority: AccountMeta,

        pub program: AccountMeta,
    }

    /// Account pubkeys for Resolve instruction
    #[derive(Debug, Clone)]
    pub struct ResolveInstructionAccounts {
        pub resolver: Pubkey,

        pub config: Pubkey,

        pub wager: Pubkey,

        pub winner: Pubkey,

        pub winner_token: Pubkey,

        pub fee_token: Pubkey,

        pub vault: Pubkey,

        pub counter_a: Pubkey,

        pub counter_b: Pubkey,

        pub rent_collector: Pubkey,

        pub event_authority: Pubkey,

        pub program: Pubkey,
    }

    impl ResolveInstructionAccounts {
        pub fn new(
            resolver: Pubkey,

            config: Pubkey,

            wager: Pubkey,

            winner: Pubkey,

            winner_token: Pubkey,

            fee_token: Pubkey,

            vault: Pubkey,

            counter_a: Pubkey,

            counter_b: Pubkey,

            rent_collector: Pubkey,

            event_authority: Pubkey,

            program: Pubkey,
        ) -> Self {
            Self {
                resolver,

                config,

                wager,

                winner,

                winner_token,

                fee_token,

                vault,

                counter_a,

                counter_b,

                rent_collector,

                event_authority,

                program,
            }
        }
    }

    /// Instruction data for Resolve
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ResolveInstructionData {
        pub winner: Pubkey,
    }

    impl ResolveInstructionData {
        pub fn new(winner: Pubkey) -> Self {
            Self { winner }
        }
    }

    /// Implementation for ResolveInstruction
    impl ResolveInstruction {
        fn discriminator() -> [u8; 8] {
            [246u8, 150u8, 236u8, 206u8, 108u8, 63u8, 58u8, 10u8]
        }

        pub fn data(data: ResolveInstructionData) -> Self {
            Self {
                accounts: ResolveInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ResolveInstructionAccounts) -> Self {
            self.accounts.resolver = AccountMeta::new_readonly(accounts.resolver, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.wager = AccountMeta::new(accounts.wager, false);

            self.accounts.winner = AccountMeta::new_readonly(accounts.winner, false);

            self.accounts.winner_token = AccountMeta::new(accounts.winner_token, false);

            self.accounts.fee_token = AccountMeta::new(accounts.fee_token, false);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.counter_a = AccountMeta::new(accounts.counter_a, false);

            self.accounts.counter_b = AccountMeta::new(accounts.counter_b, false);

            self.accounts.rent_collector = AccountMeta::new(accounts.rent_collector, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self.accounts.event_authority =
                AccountMeta::new_readonly(accounts.event_authority, false);

            self.accounts.program = AccountMeta::new_readonly(accounts.program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.resolver.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.wager.clone());

            metas.push(self.accounts.winner.clone());

            metas.push(self.accounts.winner_token.clone());

            metas.push(self.accounts.fee_token.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.counter_a.clone());

            metas.push(self.accounts.counter_b.clone());

            metas.push(self.accounts.rent_collector.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.event_authority.clone());

            metas.push(self.accounts.program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: StakeSide
    // ....................................................................

    /// Main instruction struct for StakeSide
    pub struct StakeSideInstruction {
        pub accounts: StakeSideInstructionAccountMetas,
        pub data: StakeSideInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for StakeSide instruction
    #[derive(Debug, Clone, Default)]
    pub struct StakeSideInstructionAccountMetas {
        pub staker: AccountMeta,

        pub payer: AccountMeta,

        pub config: AccountMeta,

        pub wager: AccountMeta,

        pub counter: AccountMeta,

        pub staker_token: AccountMeta,

        pub vault: AccountMeta,

        pub token_program: AccountMeta,

        pub system_program: AccountMeta,

        pub event_authority: AccountMeta,

        pub program: AccountMeta,
    }

    /// Account pubkeys for StakeSide instruction
    #[derive(Debug, Clone)]
    pub struct StakeSideInstructionAccounts {
        pub staker: Pubkey,

        pub payer: Pubkey,

        pub config: Pubkey,

        pub wager: Pubkey,

        pub counter: Pubkey,

        pub staker_token: Pubkey,

        pub vault: Pubkey,

        pub event_authority: Pubkey,

        pub program: Pubkey,
    }

    impl StakeSideInstructionAccounts {
        pub fn new(
            staker: Pubkey,

            payer: Pubkey,

            config: Pubkey,

            wager: Pubkey,

            counter: Pubkey,

            staker_token: Pubkey,

            vault: Pubkey,

            event_authority: Pubkey,

            program: Pubkey,
        ) -> Self {
            Self {
                staker,

                payer,

                config,

                wager,

                counter,

                staker_token,

                vault,

                event_authority,

                program,
            }
        }
    }

    /// Instruction data for StakeSide
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct StakeSideInstructionData {}

    impl StakeSideInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for StakeSideInstruction
    impl StakeSideInstruction {
        fn discriminator() -> [u8; 8] {
            [87u8, 92u8, 180u8, 95u8, 96u8, 113u8, 66u8, 242u8]
        }

        pub fn data(data: StakeSideInstructionData) -> Self {
            Self {
                accounts: StakeSideInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: StakeSideInstructionAccounts) -> Self {
            self.accounts.staker = AccountMeta::new_readonly(accounts.staker, true);

            self.accounts.payer = AccountMeta::new(accounts.payer, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.wager = AccountMeta::new(accounts.wager, false);

            self.accounts.counter = AccountMeta::new(accounts.counter, false);

            self.accounts.staker_token = AccountMeta::new(accounts.staker_token, false);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self.accounts.event_authority =
                AccountMeta::new_readonly(accounts.event_authority, false);

            self.accounts.program = AccountMeta::new_readonly(accounts.program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.staker.clone());

            metas.push(self.accounts.payer.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.wager.clone());

            metas.push(self.accounts.counter.clone());

            metas.push(self.accounts.staker_token.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.push(self.accounts.event_authority.clone());

            metas.push(self.accounts.program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: UnstakeSide
    // ....................................................................

    /// Main instruction struct for UnstakeSide
    pub struct UnstakeSideInstruction {
        pub accounts: UnstakeSideInstructionAccountMetas,
        pub data: UnstakeSideInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for UnstakeSide instruction
    #[derive(Debug, Clone, Default)]
    pub struct UnstakeSideInstructionAccountMetas {
        pub staker: AccountMeta,

        pub config: AccountMeta,

        pub wager: AccountMeta,

        pub counter: AccountMeta,

        pub staker_token: AccountMeta,

        pub vault: AccountMeta,

        pub token_program: AccountMeta,

        pub event_authority: AccountMeta,

        pub program: AccountMeta,
    }

    /// Account pubkeys for UnstakeSide instruction
    #[derive(Debug, Clone)]
    pub struct UnstakeSideInstructionAccounts {
        pub staker: Pubkey,

        pub config: Pubkey,

        pub wager: Pubkey,

        pub counter: Pubkey,

        pub staker_token: Pubkey,

        pub vault: Pubkey,

        pub event_authority: Pubkey,

        pub program: Pubkey,
    }

    impl UnstakeSideInstructionAccounts {
        pub fn new(
            staker: Pubkey,

            config: Pubkey,

            wager: Pubkey,

            counter: Pubkey,

            staker_token: Pubkey,

            vault: Pubkey,

            event_authority: Pubkey,

            program: Pubkey,
        ) -> Self {
            Self {
                staker,

                config,

                wager,

                counter,

                staker_token,

                vault,

                event_authority,

                program,
            }
        }
    }

    /// Instruction data for UnstakeSide
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UnstakeSideInstructionData {}

    impl UnstakeSideInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for UnstakeSideInstruction
    impl UnstakeSideInstruction {
        fn discriminator() -> [u8; 8] {
            [118u8, 120u8, 14u8, 146u8, 82u8, 45u8, 4u8, 227u8]
        }

        pub fn data(data: UnstakeSideInstructionData) -> Self {
            Self {
                accounts: UnstakeSideInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UnstakeSideInstructionAccounts) -> Self {
            self.accounts.staker = AccountMeta::new_readonly(accounts.staker, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.wager = AccountMeta::new(accounts.wager, false);

            self.accounts.counter = AccountMeta::new(accounts.counter, false);

            self.accounts.staker_token = AccountMeta::new(accounts.staker_token, false);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
                false,
            );

            self.accounts.event_authority =
                AccountMeta::new_readonly(accounts.event_authority, false);

            self.accounts.program = AccountMeta::new_readonly(accounts.program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.staker.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.wager.clone());

            metas.push(self.accounts.counter.clone());

            metas.push(self.accounts.staker_token.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.event_authority.clone());

            metas.push(self.accounts.program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: UpdateConfig
    // ....................................................................

    /// Main instruction struct for UpdateConfig
    pub struct UpdateConfigInstruction {
        pub accounts: UpdateConfigInstructionAccountMetas,
        pub data: UpdateConfigInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for UpdateConfig instruction
    #[derive(Debug, Clone, Default)]
    pub struct UpdateConfigInstructionAccountMetas {
        pub admin: AccountMeta,

        pub config: AccountMeta,
    }

    /// Account pubkeys for UpdateConfig instruction
    #[derive(Debug, Clone)]
    pub struct UpdateConfigInstructionAccounts {
        pub admin: Pubkey,

        pub config: Pubkey,
    }

    impl UpdateConfigInstructionAccounts {
        pub fn new(admin: Pubkey, config: Pubkey) -> Self {
            Self { admin, config }
        }
    }

    /// Instruction data for UpdateConfig
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UpdateConfigInstructionData {
        pub args: UpdateConfigArgs,
    }

    impl UpdateConfigInstructionData {
        pub fn new(args: UpdateConfigArgs) -> Self {
            Self { args }
        }
    }

    /// Implementation for UpdateConfigInstruction
    impl UpdateConfigInstruction {
        fn discriminator() -> [u8; 8] {
            [29u8, 158u8, 252u8, 191u8, 10u8, 83u8, 219u8, 99u8]
        }

        pub fn data(data: UpdateConfigInstructionData) -> Self {
            Self {
                accounts: UpdateConfigInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UpdateConfigInstructionAccounts) -> Self {
            self.accounts.admin = AccountMeta::new_readonly(accounts.admin, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.config.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

/// Custom struct: AdminTransfer
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct AdminTransfer {
    pub proposed: Pubkey,

    pub bump: u8,
}

impl AdminTransfer {
    pub fn new(proposed: Pubkey, bump: u8) -> Self {
        Self { proposed, bump }
    }
}

/// Custom struct: AdminTransferCancelled
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct AdminTransferCancelled {
    pub proposed: Pubkey,
}

impl AdminTransferCancelled {
    pub fn new(proposed: Pubkey) -> Self {
        Self { proposed }
    }
}

/// Custom struct: AdminTransferProposed
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct AdminTransferProposed {
    pub proposed: Pubkey,
}

impl AdminTransferProposed {
    pub fn new(proposed: Pubkey) -> Self {
        Self { proposed }
    }
}

/// Custom struct: AdminTransferred
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct AdminTransferred {
    pub previous: Pubkey,

    pub admin: Pubkey,
}

impl AdminTransferred {
    pub fn new(previous: Pubkey, admin: Pubkey) -> Self {
        Self { previous, admin }
    }
}

/// Custom struct: CancelCleared
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct CancelCleared {
    pub wager: Pubkey,

    pub by: Pubkey,
}

impl CancelCleared {
    pub fn new(wager: Pubkey, by: Pubkey) -> Self {
        Self { wager, by }
    }
}

/// Custom struct: CancelProposed
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct CancelProposed {
    pub wager: Pubkey,

    pub by: Pubkey,
}

impl CancelProposed {
    pub fn new(wager: Pubkey, by: Pubkey) -> Self {
        Self { wager, by }
    }
}

/// Custom struct: Config
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Config {
    pub admin: Pubkey,

    pub mint: Pubkey,

    pub fee_bps: u16,

    pub fee_destination: Pubkey,

    pub rent_collector: Pubkey,

    pub min_stake: u64,

    pub max_stake: u64,

    pub max_open_per_wallet: u8,

    pub resolver_allowlist: [Pubkey; 4],

    pub resolver_count: u8,

    pub paused: bool,

    pub max_window: i64,

    pub max_total_open: u64,

    pub total_open_value: u64,

    pub bump: u8,
}

impl Config {
    pub fn new(
        admin: Pubkey,

        mint: Pubkey,

        fee_bps: u16,

        fee_destination: Pubkey,

        rent_collector: Pubkey,

        min_stake: u64,

        max_stake: u64,

        max_open_per_wallet: u8,

        resolver_allowlist: [Pubkey; 4],

        resolver_count: u8,

        paused: bool,

        max_window: i64,

        max_total_open: u64,

        total_open_value: u64,

        bump: u8,
    ) -> Self {
        Self {
            admin,

            mint,

            fee_bps,

            fee_destination,

            rent_collector,

            min_stake,

            max_stake,

            max_open_per_wallet,

            resolver_allowlist,

            resolver_count,

            paused,

            max_window,

            max_total_open,

            total_open_value,

            bump,
        }
    }
}

/// Custom struct: CreateWagerArgs
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct CreateWagerArgs {
    pub nonce: u64,

    pub side_a: Pubkey,

    pub side_b: Pubkey,

    pub stake: u64,

    pub terms_hash: [u8; 32],

    pub deadline_fund: i64,

    pub deadline_resolve: i64,

    pub resolver: Pubkey,
}

impl CreateWagerArgs {
    pub fn new(
        nonce: u64,

        side_a: Pubkey,

        side_b: Pubkey,

        stake: u64,

        terms_hash: [u8; 32],

        deadline_fund: i64,

        deadline_resolve: i64,

        resolver: Pubkey,
    ) -> Self {
        Self {
            nonce,

            side_a,

            side_b,

            stake,

            terms_hash,

            deadline_fund,

            deadline_resolve,

            resolver,
        }
    }
}

/// Custom struct: ExposureCounter
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct ExposureCounter {
    pub count: u8,

    pub bump: u8,
}

impl ExposureCounter {
    pub fn new(count: u8, bump: u8) -> Self {
        Self { count, bump }
    }
}

/// Custom struct: InitializeConfigArgs
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct InitializeConfigArgs {
    pub mint: Pubkey,

    pub fee_bps: u16,

    pub fee_destination: Pubkey,

    pub rent_collector: Pubkey,

    pub min_stake: u64,

    pub max_stake: u64,

    pub max_open_per_wallet: u8,

    pub resolvers: Vec<Pubkey>,

    pub max_window: i64,

    pub max_total_open: u64,
}

impl InitializeConfigArgs {
    pub fn new(
        mint: Pubkey,

        fee_bps: u16,

        fee_destination: Pubkey,

        rent_collector: Pubkey,

        min_stake: u64,

        max_stake: u64,

        max_open_per_wallet: u8,

        resolvers: Vec<Pubkey>,

        max_window: i64,

        max_total_open: u64,
    ) -> Self {
        Self {
            mint,

            fee_bps,

            fee_destination,

            rent_collector,

            min_stake,

            max_stake,

            max_open_per_wallet,

            resolvers,

            max_window,

            max_total_open,
        }
    }
}

/// Custom struct: SideRefunded
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct SideRefunded {
    pub wager: Pubkey,

    pub side: Pubkey,

    pub amount: u64,
}

impl SideRefunded {
    pub fn new(wager: Pubkey, side: Pubkey, amount: u64) -> Self {
        Self {
            wager,

            side,

            amount,
        }
    }
}

/// Custom struct: SideStaked
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct SideStaked {
    pub wager: Pubkey,

    pub staker: Pubkey,

    pub is_side_a: bool,

    pub amount: u64,

    pub now_active: bool,
}

impl SideStaked {
    pub fn new(
        wager: Pubkey,

        staker: Pubkey,

        is_side_a: bool,

        amount: u64,

        now_active: bool,
    ) -> Self {
        Self {
            wager,

            staker,

            is_side_a,

            amount,

            now_active,
        }
    }
}

/// Custom struct: SideUnstaked
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct SideUnstaked {
    pub wager: Pubkey,

    pub staker: Pubkey,

    pub amount: u64,
}

impl SideUnstaked {
    pub fn new(wager: Pubkey, staker: Pubkey, amount: u64) -> Self {
        Self {
            wager,

            staker,

            amount,
        }
    }
}

/// Custom struct: UpdateConfigArgs
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct UpdateConfigArgs {
    pub fee_bps: Option<u16>,

    pub fee_destination: Option<Pubkey>,

    pub rent_collector: Option<Pubkey>,

    pub min_stake: Option<u64>,

    pub max_stake: Option<u64>,

    pub max_open_per_wallet: Option<u8>,

    pub resolvers: Option<Vec<Pubkey>>,

    pub paused: Option<bool>,

    pub max_window: Option<i64>,

    pub max_total_open: Option<u64>,
}

impl UpdateConfigArgs {
    pub fn new(
        fee_bps: Option<u16>,

        fee_destination: Option<Pubkey>,

        rent_collector: Option<Pubkey>,

        min_stake: Option<u64>,

        max_stake: Option<u64>,

        max_open_per_wallet: Option<u8>,

        resolvers: Option<Vec<Pubkey>>,

        paused: Option<bool>,

        max_window: Option<i64>,

        max_total_open: Option<u64>,
    ) -> Self {
        Self {
            fee_bps,

            fee_destination,

            rent_collector,

            min_stake,

            max_stake,

            max_open_per_wallet,

            resolvers,

            paused,

            max_window,

            max_total_open,
        }
    }
}

/// Custom struct: Wager
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Wager {
    pub state: WagerState,

    pub side_a: Pubkey,

    pub side_b: Pubkey,

    pub stake: u64,

    pub mint: Pubkey,

    pub funded_a: bool,

    pub funded_b: bool,

    pub refunded_a: bool,

    pub refunded_b: bool,

    pub resolver: Pubkey,

    pub terms_hash: [u8; 32],

    pub deadline_fund: i64,

    pub deadline_resolve: i64,

    pub fee_bps: u16,

    pub fee_destination: Pubkey,

    pub rent_collector: Pubkey,

    pub nonce: u64,

    pub cancel_proposed_by: Pubkey,

    pub bump: u8,
}

impl Wager {
    pub fn new(
        state: WagerState,

        side_a: Pubkey,

        side_b: Pubkey,

        stake: u64,

        mint: Pubkey,

        funded_a: bool,

        funded_b: bool,

        refunded_a: bool,

        refunded_b: bool,

        resolver: Pubkey,

        terms_hash: [u8; 32],

        deadline_fund: i64,

        deadline_resolve: i64,

        fee_bps: u16,

        fee_destination: Pubkey,

        rent_collector: Pubkey,

        nonce: u64,

        cancel_proposed_by: Pubkey,

        bump: u8,
    ) -> Self {
        Self {
            state,

            side_a,

            side_b,

            stake,

            mint,

            funded_a,

            funded_b,

            refunded_a,

            refunded_b,

            resolver,

            terms_hash,

            deadline_fund,

            deadline_resolve,

            fee_bps,

            fee_destination,

            rent_collector,

            nonce,

            cancel_proposed_by,

            bump,
        }
    }
}

/// Custom struct: WagerCancelled
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct WagerCancelled {
    pub wager: Pubkey,
}

impl WagerCancelled {
    pub fn new(wager: Pubkey) -> Self {
        Self { wager }
    }
}

/// Custom struct: WagerClosed
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct WagerClosed {
    pub wager: Pubkey,

    pub surplus_swept: u64,
}

impl WagerClosed {
    pub fn new(wager: Pubkey, surplus_swept: u64) -> Self {
        Self {
            wager,

            surplus_swept,
        }
    }
}

/// Custom struct: WagerConceded
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct WagerConceded {
    pub wager: Pubkey,

    pub conceder: Pubkey,

    pub winner: Pubkey,

    pub payout: u64,

    pub fee: u64,
}

impl WagerConceded {
    pub fn new(wager: Pubkey, conceder: Pubkey, winner: Pubkey, payout: u64, fee: u64) -> Self {
        Self {
            wager,

            conceder,

            winner,

            payout,

            fee,
        }
    }
}

/// Custom struct: WagerCreated
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct WagerCreated {
    pub wager: Pubkey,

    pub side_a: Pubkey,

    pub side_b: Pubkey,

    pub stake: u64,

    pub mint: Pubkey,

    pub resolver: Pubkey,

    pub terms_hash: [u8; 32],

    pub deadline_fund: i64,

    pub deadline_resolve: i64,

    pub nonce: u64,
}

impl WagerCreated {
    pub fn new(
        wager: Pubkey,

        side_a: Pubkey,

        side_b: Pubkey,

        stake: u64,

        mint: Pubkey,

        resolver: Pubkey,

        terms_hash: [u8; 32],

        deadline_fund: i64,

        deadline_resolve: i64,

        nonce: u64,
    ) -> Self {
        Self {
            wager,

            side_a,

            side_b,

            stake,

            mint,

            resolver,

            terms_hash,

            deadline_fund,

            deadline_resolve,

            nonce,
        }
    }
}

/// Custom struct: WagerResolved
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct WagerResolved {
    pub wager: Pubkey,

    pub winner: Pubkey,

    pub payout: u64,

    pub fee: u64,
}

impl WagerResolved {
    pub fn new(wager: Pubkey, winner: Pubkey, payout: u64, fee: u64) -> Self {
        Self {
            wager,

            winner,

            payout,

            fee,
        }
    }
}

/// Custom enum: WagerState
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub enum WagerState {
    Funding,

    Active,

    Resolved,

    Cancelled,
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
